package try_catch;

public class RunMain {
  // Checked -> code
  // Uncheck -> Run
  public static void main(String[] args) {
//    OutputStream outputStream = null;
//    try {
//      outputStream = new FileOutputStream("demoZipFile.zip");
//
//      int a = 0;
//
//      int avg = 10 / 1;
//
//      System.out.println(avg);
//
//
//    } catch (Exception ex) {
//      System.out.println("Đang chia cho số 0 bắt bởi class ArithmeticException");
//      System.out.println("Message: " + ex.getMessage());
//    } finally {
//      System.out.println("Chạy every time");
//        try {
//          outputStream.close();
//        } catch (IOException e) {
//
//        }
//    }

//    try {
//      Print();
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    }

//    Print();

  }

  //throws: Không thực hiện xử lý lỗi
  //Đẩy cho thằng nào gọi thì tự xử lý
  private static void Print() {
//    System.out.println("ABC");
//    Print();
  }


}
